// _rafce */
const  HEAD =()=>{
    return(
        <DIV>

        </DIV>
    )
}
export default HEAD
                    
/* WE NEED webpack bcoz all our react code and components has to be compiled &  bundled in one js file ---- bundles assests together*/
/* babble transpile  code down to browser friendly code depending on which browser is being used..*/
/* webpack plugin creates html file in dist folder */
/* React Router’s whole job is to render specific components based on the
current URL path */
/*  REDUX= Instead of having state spread out
in different places, with Redux you stick all of your state in a single location
called a Store. You then establish strict rules for how the state of your Store
can change.*/
/* props cant be changed directly */